In [ ]:
import seaborn as sns
import pandas as pd
import numpy as np
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.neighbors import KNeighborsClassifier
import sys
import json
import pickle
import warnings
warnings.filterwarnings('ignore')

In [17]:
class knn:
  try:
    def __init__(self):
      self.df = sns.load_dataset('iris')
      self.df['species'] = self.df['species'].map({'setosa':0,'versicolor':1,'virginica':2}).astype(int)
      self.X = self.df.iloc[:,:-1]
      self.y = self.df.iloc[:,-1]
      self.X_train,self.X_test,self.y_train,self.y_test = train_test_split(self.X,self.y,test_size = 0.2,random_state=45)
      self.reg = KNeighborsClassifier()
      self.reg.fit(self.X_train,self.y_train)
    def test_data(self):
      self.cmm = confusion_matrix(self.y_test,self.reg.predict(self.X_test))
      self.acs = accuracy_score(self.y_test,self.reg.predict(self.X_test))
      self.clrr = classification_report(self.y_test,self.reg.predict(self.X_test))
      print(self.cmm)
      print(self.acs)
      print(self.clrr)
      self.result = {
          "confusion_matrix" : self.cmm.tolist(),
          "acccuracy_score": self.acs,
          "class_report" : self.clrr

      }
      with open("knn_test.json",'w')as f:
        json.dump(self.result,f,indent=4)
      with open('knn_algoritm.pkl','wb')as dym:
        pickle.dump(self.reg,dym)

  except Exception:
    exc_type,exc_msg,exc_line = sys.info()
    print(exc_type,exc_msg,exc_line)



if __name__ == '__main__':
  obj = knn()
  obj.test_data()



[[11  0  0]
 [ 0  7  0]
 [ 0  1 11]]
0.9666666666666667
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       0.88      1.00      0.93         7
           2       1.00      0.92      0.96        12

    accuracy                           0.97        30
   macro avg       0.96      0.97      0.96        30
weighted avg       0.97      0.97      0.97        30



In [19]:
with open('knn_algoritm.pkl','rb') as manish:
  fgj = pickle.load(manish)
print(fgj.predict([[5.1,3.8,1.9,0.4]]))

[0]
