In [18]:
import seaborn as sns
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import pickle
import sys
import sklearn
import warnings
warnings.filterwarnings('ignore')
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.naive_bayes import GaussianNB

In [23]:
class kpr:
  try:
    def __init__(self):
      self.df = sns.load_dataset('iris')
      self.df['species'] = self.df['species'].map({'setosa':0,'versicolor':1,'virginica':2})
      self.X = self.df.iloc[:,:-1]
      self.y = self.df.iloc[:,-1]
      self.X_train,self.X_test,self.y_train,self.y_test = train_test_split(self.X,self.y,test_size=0.2,random_state=45)
      self.reg = GaussianNB()
      self.reg.fit(self.X_train,self.y_train)
    def train(self):
      self.cmpr = confusion_matrix(self.y_test,self.reg.predict(self.X_test))
      self.acrs = accuracy_score(self.y_test,self.reg.predict(self.X_test))
      self.conf = classification_report(self.y_test,self.reg.predict(self.X_test))
      print(self.cmpr)
      print(self.acrs)
      print(self.conf)
  except Exception:
    exc_type,exc_msg,exc_line = sys.info()
    print(exc_type,exc_msg,exc_line)


if __name__ =='__main__':
  obj = kpr()
  obj.train()


[[11  0  0]
 [ 0  7  0]
 [ 0  1 11]]
0.9666666666666667
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       0.88      1.00      0.93         7
           2       1.00      0.92      0.96        12

    accuracy                           0.97        30
   macro avg       0.96      0.97      0.96        30
weighted avg       0.97      0.97      0.97        30

